config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'negotiations#index'
  resources :users
  resources :customers
  resources :negotiations do
    collection do
      get :negotiation_list
    end
    resources :continuations do
      resources :cnt_comments
    end
    resources :comments
  end

  resources :notifications, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/continuation.rb
class Continuation < ApplicationRecord
  belongs_to :negotiation
  belongs_to :user
  has_many :cnt_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :text, presence: true, length: {in: 1..500}
  validates :year, presence: true
  validates :month, presence: true
  validates :day, presence: true

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      continuation_id: id,
      visited_id: negotiation.user_id,
      action: "continuation"
    )
    notification.save if negotiation.user_id != current_user.id
  end
end

app/controllers/continuations_controller.rb
class ContinuationsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_continuation, only: [:edit, :show, :update, :destroy]
  before_action :set_negotiation

  def new
    @continuation = Continuation.new
  end

  def show
    @ccomments = @continuation.cnt_comments.includes(:user)
  end

  def create
    @continuation = @negotiation.continuations.new(conti_params)
    if @continuation.save
      @continuation.create_notification_by(current_user)
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @continuation.update(conti_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @continuation.destroy
      redirect_to  root_path
    else
      render :edit
    end
  end

  private
  def conti_params
    params.require(:continuation).permit(:text, :user_id, :year, :month, :day, :way, :next_nego, :next_year, :next_month, :next_day).merge(negotiation_id: @negotiation.id)
  end

  def set_negotiation
    @negotiation = Negotiation.find(params[:negotiation_id])
  end

  def set_continuation
    @continuation = Continuation.find(params[:id])
  end
end

app/views/continuations/_continuation.html.haml
- if @continuations
  - @continuations.each do |cont|
    .continuation-container
      .main-nego
        .main-nego__detail
          .main-nego__detail__head
            .main-nego__detail__head__title
              %p
                #{cont.year}年 #{cont.month}月 #{cont.day}日
            .main-nego__detail__head__user
              %p
                担当：#{cont.user.last_name} #{cont.user.first_name}
          .main-nego__detail__box
            .main-nego__detail__box__body
              = safe_join(cont.text.split("\n"), tag(:br))
          .main-nego__detail__box
            .main-nego__detail__box__container
              %p
                次回：
            - if cont.next_nego == "あり"
              .main-nego__detail__box__container
                %p.next-nego-text
                  #{cont.next_year}年 #{cont.next_month}月 #{cont.next_day}日
            - else
              %p
                = cont.next_nego
          .main-nego__detail__box
            .main-nego__detail__box__menu
              = link_to "経過登録", new_negotiation_continuation_path(@negotiation.id), data: {"turbolinks" => false}, class: "continuation-btn menu-btn"
              = link_to "コメントする", negotiation_continuation_path(@negotiation.id, cont.id), class: "comment-btn menu-btn"
              - if cont.cnt_comments.length != 0
                = link_to negotiation_continuation_path(@negotiation.id, cont.id), class: "comment-btn menu-btn" do
                  %i.far.fa-comment
                  = cont.cnt_comments.length

app/views/continuations/edit.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__container.nego-back
      %h2
        経過進捗の編集
      = form_with model: @continuation, url: negotiation_continuation_path, method: :patch, local: true do |f|

        .field
          = f.label :商談内容
          %span.require 必須
          = f.text_area :text, class: "require-check-body"

        .field
          = f.label :担当者
          = f.collection_select :user_id, User.all, :id, :view_last_name_and_first_name, {prompt: "--"}
          %span.require 必須

        .field
          = f.label :対応年月日
          %span.require 必須
          %br/  
          .wrap
            .select
              = f.select :year, [], {prompt: "--"}, {class: "select-year"}
            %span 年
            .select
              = f.select :month, [], {prompt: "--"}, {class: "select-month"}
            %span 月
            .select
              = f.select :day, [], {prompt: "--"}, {class: "select-day"}
            %span 日

        .field
          = f.label :応対方法
          %span.require 必須
          = f.select :way, ["面会", "電話", "メール", "書面", "その他"], {prompt: "--"}

        .field
          = f.label :次回対応
          = f.select :next_nego, ["あり", "なし", "未定"], {prompt: "--"}, {id: "next-cnt"}

        .next-negotiation-box
        
        = f.submit '編集', class: "submit-btn submit-nego"

app/views/continuations/new.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__container.nego-back
      %h2
        経過進捗の登録
      = form_with model: @continuation, url: negotiation_continuations_path, local: true do |f|

        .field
          = f.label :商談内容
          %span.require 必須
          = f.text_area :text, class: "require-check-body"
        
        .field
          = f.label :担当者
          = f.collection_select :user_id, User.all, :id, :view_last_name_and_first_name, {prompt: "--"}
          %span.require 必須

        .field
          = f.label :対応年月日
          %span.require 必須
          %br/  
          .wrap
            .select
              = f.select :year, [], {prompt: "--"}, {class: "select-year"}
            %span 年
            .select
              = f.select :month, [], {prompt: "--"}, {class: "select-month"}
            %span 月
            .select
              = f.select :day, [], {prompt: "--"}, {class: "select-day"}
            %span 日

        .field
          = f.label :応対方法
          %span.require 必須
          = f.select :way, ["面会", "電話", "メール", "書面", "その他"], {prompt: "--"}

        .field
          = f.label :次回対応
          = f.select :next_nego, ["あり", "なし", "未定"], {prompt: "--"}, {id: "next-cnt"}

        .next-negotiation-box
        
        = f.submit '登録', class: "submit-btn submit-nego"

app/views/continuations/show.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__detail
      .main-nego__detail__head
        .main-nego__detail__head__title
          = link_to :back do
            %i.fas.fa-chevron-left
          %p.nego-title
            = @negotiation.title
        .main-nego__detail__head__menu
          %i.fas.fa-angle-down
        .main-nego__detail__head__menu__window{ style: "display:none" }
          %li
            = link_to "編集", edit_negotiation_continuation_path, data: {"turbolinks" => false}, class: "menu-btn"
            %br/
          %li
            = link_to "削除", negotiation_continuation_path, method: :delete, class: "confirm-btn menu-btn"
      .main-nego__detail__head
        .main-nego__detail__head__title
          %p
            #{@continuation.year}年 #{@continuation.month}月 #{@continuation.day}日
        .main-nego__detail__head__user
          %p
            担当：#{@continuation.user.last_name} #{@continuation.user.first_name}
      .main-nego__detail__box
        .main-nego__detail__box__body
          = safe_join(@continuation.text.split("\n"), tag(:br))
      .main-nego__detail__box
        .main-nego__detail__box__container
          %p
            次回：
        - if @continuation.next_nego == "あり"
          .main-nego__detail__box__container
            %p.next-nego-text
              #{@continuation.next_year}年 #{@continuation.next_month}月 #{@continuation.next_day}日
        - else
          %p
            = @continuation.next_nego
      .main-nego__detail__box
        .main-nego__detail__box__menu
          = link_to "経過登録", new_negotiation_continuation_path(@negotiation.id), data: {"turbolinks" => false}, class: "continuation-btn menu-btn"
          %a.comment-box-btn.menu-btn{ style: "display:none" }
            コメントする
      .main-nego__detail__box
        .main-nego__detail__box__comment
          = form_with model: @cnt_comment, url: negotiation_continuation_cnt_comments_path(@negotiation.id, @continuation.id), local: true do |c|
            .field
              = c.label :コメント
              %span.cancel-btn
                %i.fas.fa-times-circle
              %br/
              = c.text_area :body, class: "comment-area"
              
              = c.submit 'コメントする', class: "comment-submit menu-btn"

    = render partial: "cnt_comments/cnt_comment", collection: @ccomments