config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'negotiations#index'
  resources :users
  resources :customers
  resources :negotiations do
    collection do
      get :negotiation_list
    end
    resources :continuations do
      resources :cnt_comments
    end
    resources :comments
  end

  resources :notifications, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.haml
.header
  .title-box
    =link_to root_path do
      .title
        %h1
          ProgRecord
        %p.subtitle
          Progress + Record

  .nav-ver
    %ul.nav-ver-item-left
      %li.nav-ver-item-left__customers.dropdwn
        %p
          %i.fas.fa-building
          取引先
          %i.fas.fa-caret-down
        %ul.dropdwn_menu
          %li
            = link_to "取引先一覧", customers_path
          %li
            = link_to "取引先登録", new_customer_path
      %li.nav-ver-item-left__negotiation.dropdwn
        %p
          %i.fas.fa-hands-helping
          商談記録
          %i.fas.fa-caret-down
        %ul.dropdwn_menu
          %li
            = link_to "商談記録一覧", negotiation_list_negotiations_path, data: {"turbolinks" => false}
          %li
            = link_to "商談記録登録", new_negotiation_path, data: {"turbolinks" => false}
    %ul.nav-ver-item
      - if user_signed_in?
        %li.nav-ver-item__info
          = link_to notifications_path do
            %i.far.fa-bell.notification
            - if unchecked_notifications.any?
              - if @exist > 99
                %span.notification-count
                  +99
              - elsif @exist != 0
                %span.notification-count
                  #{@exist}
      %li.nav-ver-item__user.dropdwn
        - if user_signed_in?
          .nav-ver-item__user__name
            %i.fas.fa-portrait
            = current_user.last_name
            = current_user.first_name
            %i.fas.fa-caret-down
          %ul.dropdwn_menu
            %li
              = link_to "マイページ",user_path(current_user.id)
            %li
              = link_to "ログアウト",destroy_user_session_path, method: :delete
            %li
              
            %li

        - else
          = link_to "新規登録", new_user_registration_path, class: "sign-up-btn"
          = link_to "ログイン", new_user_session_path, class: "sign-in-btn"