config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'negotiations#index'
  resources :users
  resources :customers
  resources :negotiations do
    collection do
      get :negotiation_list
    end
    resources :continuations do
      resources :cnt_comments
    end
    resources :comments
  end

  resources :notifications, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :negotiations
  belongs_to :category

  validates :name, presence: true
  validates :category_id, presence: true
  validates :person, presence: true
  validates :mobile, format: {
                      with: /A0[789]0\d{8}z/
                    }, allow_blank: true

  validates :tel, format: {
                    with: /A0\d{9,10}z/
                  }, allow_blank: true

  validates :fax, format: {
                    with: /A0\d{9,10}z/
                  }, allow_blank: true

  validates :email, format: {
                      with: /\A\S+@\S+\.\S+\z/
                    }, allow_blank: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.where(params[:id])
    @cs_search = Customer.ransack(params[:q])
    @cs_result = @cs_search.result.page(params[:page]).per(10).order("created_at DESC")
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(new_params)
    if @customer.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @customer.update(new_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @customer.destroy
      redirect_to  root_path
    else
      render :index
    end
  end

  private
  def new_params
    params.require(:customer).permit(:name, :category_id, :person, :position, :tel, :mobile, :fax, :email, :product, :remarks)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/views/customers/_customer.html.haml
= link_to customer_path(customer.id) do
  .customer-box
    .customer__body
      #{customer.name} (#{customer.category.name})

app/views/customers/edit.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__container.customer-back
      %h2
        取引先の編集
      = form_with model: @customer, method: :patch, local: true do |f|

        .field
          = f.label :会社名
          %span.require 必須
          %br/
          = f.text_field :name, class: "require-check-customer"

        .field
          = f.label :カテゴリ
          %span.require 必須
          %br/
          = f.select :category, ["事務用品", "医療材料", "検査試薬", "医薬品"]

        .field
          = f.label :営業担当
          %span.require 必須
          = f.text_field :person, class: "require-check-person"

        .field
          = f.label :役職
          = f.select :position, ["担当", "主任級", "営業所長", "エリア長", "社長"]

        .field
          = f.label :電話番号
          = f.text_field :tel, placeholder: "ハイフン無し", class: "telephone"

        .field
          = f.label :営業携帯電話
          = f.text_field :mobile, placeholder: "ハイフン無し", class: "mobile_phone"

        .field
          = f.label :FAX
          = f.text_field :fax, placeholder: "ハイフン無し", class: "telephone"

        .field
          = f.label :メールアドレス
          = f.text_field :email, class: "email"

        .field
          = f.label :取扱商材
          = f.text_field :product

        .field
          = f.label :備考欄
          %br/
          = f.text_area :remarks
        
        = f.submit '編集', class: "submit-btn submit-cstm"

app/views/customers/index.html.haml
= render "shared/header"
.container
  .customer-container
    .customer-container__title
      %h2
        取引先一覧
      = link_to new_customer_path do
        %i.fas.fa-edit
        取引先登録

    .list-container__search
      = search_form_for @cs_search , url: customers_path do |f|
        .list-container__search__area
          %i.fas.fa-search
          = f.text_field :name_or_product_or_person_cont, placeholder: "　社名 or 担当者 or 取扱商材を入力", class: "search-area"
          = f.submit "検索する", class: "search-btn"
        .list-container__search__box
          .list-container__search__box__item
            = f.label :category_id_eq, 'カテゴリー'
            = f.collection_select( :category_id_eq, Category.all, :id, :name, {include_blank: "指定なし"}, {class: "search-list"})

    .list-container__result
      - if @cs_result.any?
        %i.fas.fa-filter
        = sort_link(@cs_search, :name, "登録名")
        = sort_link(@cs_search, :updated_at, "登録順")
        = render @cs_result
    
    = paginate @cs_result

app/views/customers/new.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__container.customer-back
      %h2
        取引先の登録
      = form_with model: @customer, local: true do |f|

        .field
          = f.label :会社名
          %span.require 必須
          %br/
          = f.text_field :name, class: "require-check-customer"

        .field
          = f.label :カテゴリ
          %span.require 必須
          %br/
          = f.collection_select :category_id, Category.all, :id, :name, {prompt: "--"}

        .field
          = f.label :営業担当
          %span.require 必須
          = f.text_field :person, class: "require-check-person"

        .field
          = f.label :役職
          = f.select :position, ["担当", "主任級", "営業所長", "エリア長", "社長"], {prompt: "--"}

        .field
          = f.label :電話番号
          = f.text_field :tel, placeholder: "ハイフン無し", class: "telephone"

        .field
          = f.label :営業携帯電話
          = f.text_field :mobile, placeholder: "ハイフン無し", class: "mobile_phone"

        .field
          = f.label :FAX
          = f.text_field :fax, placeholder: "ハイフン無し", class: "telephone"

        .field
          = f.label :メールアドレス
          = f.text_field :email, class: "email"

        .field
          = f.label :取扱商材
          = f.text_field :product

        .field
          = f.label :備考欄
          = f.text_area :remarks
        
        = f.submit '登録', class: "submit-btn submit-cstm"

app/views/customers/show.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__container.customer-back
      %p.customer-category
        = @customer.category.name
      %h2.customer-name
        = @customer.name
      .customer-back__box
        %p
          %i.fas.fa-phone-square
          電話番号：#{@customer.tel} 
        %p
          %i.fas.fa-fax
          FAX：#{@customer.fax}
      .customer-back__box
        %h3.customer-person
          担当者情報
        .customer-back__box__detail
          %p
            #{@customer.person} (役職：#{@customer.position})
          %p
            %i.fas.fa-mobile-alt
            電話番号：#{@customer.mobile}
          %p
            %i.far.fa-envelope-open
            メール：#{@customer.email}
      .customer-back__box
        取扱商材：#{@customer.product}
      .customer-back__box
        %p
          ※備考
        .customer-back__box__remarks
          = safe_join(@customer.remarks.split("\n"), tag(:br))
      .customer-back__edit
        = link_to "編集", edit_customer_path, class: "customer-btn"
        = link_to "削除", customer_path, method: :delete, class: "customer-delete customer-btn"