config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'negotiations#index'
  resources :users
  resources :customers
  resources :negotiations do
    collection do
      get :negotiation_list
    end
    resources :continuations do
      resources :cnt_comments
    end
    resources :comments
  end

  resources :notifications, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/negotiation.rb
class Negotiation < ApplicationRecord
  belongs_to :user
  belongs_to :customer
  has_many :continuations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :cnt_comments, dependent: :destroy
  belongs_to :content
  belongs_to :department

  validates :title, presence: true, length: {in: 1..50}
  validates :body, presence: true, length: {in: 1..500}
  validates :year, presence: true
  validates :month, presence: true
  validates :day, presence: true
end

app/controllers/negotiations_controller.rb
class NegotiationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :negotiation_list]
  before_action :set_negotiation, only: [:show, :edit, :update, :destroy]

  def index
    @negotiations = Negotiation.where(params[:id]).order(created_at: "DESC").limit(3)
    @customers = Customer.where(params[:id]).order(created_at: "DESC").limit(3)
    @importants = Negotiation.includes(:user).where(importance: "★★★★").or(Negotiation.includes(:user).where(importance: "★★★★★")).order(created_at: "DESC").limit(3)
  end

  def show
    @continuations = @negotiation.continuations.includes(:user)
    @comments = @negotiation.comments.includes(:user)
  end

  def new
    @negotiation = Negotiation.new
  end

  def create
    @negotiation = Negotiation.new(nego_params)
    if @negotiation.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @negotiation.update(nego_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @negotiation.destroy
      redirect_to  root_path
    else
      render :index
    end
  end

  def negotiation_list
    @negotiations = Negotiation.where(params[:id])
    @search = Negotiation.ransack(params[:q])
    @result = @search.result.page(params[:page]).per(10).order("created_at DESC")
    @customers = Customer.where(params[:id])
    @users = User.where(params[:id])
  end

  def count
    @exist = Notification.where(checked: '0').count
  end

  private
  def nego_params
    params.require(:negotiation).permit(:customer_id, :user_id, :year, :month, :day, :title, :body, :content_id, :importance, :department_id, :way, :next_nego, :next_year, :next_month, :next_day)
  end

  def set_negotiation
    @negotiation = Negotiation.find(params[:id])
  end
end

app/views/negotiations/_negotiation.html.haml
= link_to negotiation_path(negotiation.id) do
  .nego-box
    .nego-box__body
      .nego-box__body__contents
        タイトル：#{negotiation.title}
      .nego-box__body__contents
        .nego-box__body__contents__element
          日付：#{negotiation.year}/#{negotiation.month}/#{negotiation.day}
        .nego-box__body__contents__element
          対応者：#{negotiation.user.last_name} #{negotiation.user.first_name}
      .nego-box__body__contents
        取引先：#{negotiation.customer.name}

app/views/negotiations/edit.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__container.nego-back
      %h2
        商談記録の編集

      = form_with model: @negotiation, method: :patch, local: true do |f|

        .field
          = f.label :会社名
          %span.require 必須
          %br/
          = f.collection_select :customer_id, Customer.all, :id, :name, {prompt: "--"}

        .field
          = f.label :担当者
          = f.collection_select :user_id, User.all, :id, :view_last_name_and_first_name, {prompt: "--"}
          %span.require 必須

        .field
          = f.label :商談種類
          %span.require 必須
          %br/
          = f.select :content, ["新規提案", "価格交渉", "契約関係", "納期調整", "その他"], {prompt: "--"}

        .field
          = f.label :対応年月日
          %span.require 必須
          %br/  
          .wrap
            .select
              = f.select :year, [], {prompt: "--"}, {class: "select-year"}
            %span 年
            .select
              = f.select :month, [], {prompt: "--"}, {class: "select-month"}
            %span 月
            .select
              = f.select :day, [], {prompt: "--"}, {class: "select-day"}
            %span 日

        .field
          = f.label :タイトル
          %span.require 必須
          = f.text_field :title, class: "title-inputbox require-check-title"

        .field
          = f.label :商談内容
          %span.require 必須
          %br/
          = f.text_area :body, class:"negotiation-body require-check-body"

        .field
          = f.label :重要度
          = f.select :importance, ["★", "★★", "★★★", "★★★★", "★★★★★"]

        .field
          = f.label :関係部署
          = f.collection_select :department_id, Department.all, :id, :name, {prompt: "--"}

        .field
          = f.label :応対方法
          %span.require 必須
          = f.select :way, ["面会", "電話", "メール", "書面", "その他"], {prompt: "--"}

        .field
          = f.label :次回対応
          = f.select :next_nego, ["あり", "なし", "未定"], {prompt: "--"}

        .field
          = f.label :次回年月日
          %span.require 必須
          %br/  
          .wrap
            .select
              = f.select :next_year, [], {prompt: "--"}, {class: "select-nyear"}
            %span 年
            .select
              = f.select :next_month, [], {prompt: "--"}, {class: "select-nmonth"}
            %span 月
            .select
              = f.select :next_day, [], {prompt: "--"}, {class: "select-nday"}
            %span 日
        
        = f.submit '編集', class: "submit-btn submit-nego"

app/views/negotiations/index.html.haml
= render "shared/header"
.main-container
  .important-negotiation
    %span.title-box
      = link_to negotiation_list_negotiations_path, data: {"turbolinks" => false} do
        %i.fas.fa-exclamation-circle
        重要商談
    - if @importants.length != 0
      = render partial: "negotiation", collection: @importants
    - else
      .important-negotiation__nothing
        %p.nothing-word
          最近の重要商談はありません
  .middle-container
    .newest-negotiation
      %span.title-box
        = link_to negotiation_list_negotiations_path, data: {"turbolinks" => false} do
          %i.fas.fa-hands-helping
          最近の商談
      - if @negotiations.length != 0
        = render partial: "negotiation", collection: @negotiations
      - else
        .newest-negotiation__nothing
          %p.nothing-word
            最近の商談はありません

    .newest-customer
      %span.title-box
        = link_to customers_path, data: {"turbolinks" => false} do
          %i.fas.fa-building
          最近追加された取引先
      - if @customers.length != 0
        = render partial: "customers/customer", collection: @customers
      - else
        .newest-customer__nothing
          %p.nothing-word
            最近追加された取引先はありません

app/views/negotiations/negotiation_list.html.haml
= render "shared/header"
.container
  .list-container
    .list-container__title
      %h2
        商談記録一覧
      = link_to new_negotiation_path do
        %i.fas.fa-edit
        商談記録登録

    .list-container__search
      = search_form_for @search , url: negotiation_list_negotiations_path do |f|
        .list-container__search__area
          %i.fas.fa-search
          = f.text_field :title_or_body_cont, class: "search-area"
          = f.submit "検索する", class: "search-btn"
        .list-container__search__box
          .list-container__search__box__item
            = f.label :customer_id_eq, '取引先'
            = f.collection_select( :customer_id_eq, @customers, :id, :name, {include_blank:  "指定なし"}, {class: "search-list"})
 
          .list-container__search__box__item
            = f.label :uer_id_eq, '担当者'
            = f.collection_select( :user_id_eq, @users, :id, :view_last_name_and_first_name, {include_blank:  "指定なし"}, {class: "search-list"})
 
          .list-container__search__box__item
            = f.label :department_id_eq, '関連部署'
            = f.collection_select( :department_id_eq, Department.all, :id, :name, {include_blank:  "指定なし"}, {class: "search-list"})

          .list-container__search__box__item
            = f.label :content_id_eq, '商談内容'
            = f.collection_select( :content_id_eq, Content.all, :id, :name, {include_blank:  "指定なし"}, {class: "search-list"})
    .list-container__result
      - if @result.any?
        %i.fas.fa-filter
        = sort_link(@search, :title, "タイトル")
        = sort_link(@search, :importance, "重要度")
        = sort_link(@search, :updated_at, "更新順")
        = render @result
    = paginate @result

app/views/negotiations/new.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__container.nego-back
      %h2
        商談記録の登録
      = form_with model: @negotiation, method: :post, local: true do |f|
        
        .field
          = f.label :タイトル
          %span.require 必須
          = f.text_field :title,class: "title-inputbox require-check-title"

        .field
          = f.label :会社名
          = f.collection_select :customer_id, Customer.all, :id, :name, {prompt: "--"}
          %span.require 必須

        .field
          = f.label :担当者
          = f.collection_select :user_id, User.all, :id, :view_last_name_and_first_name, {prompt: "--"}
          %span.require 必須

        .field
          = f.label :商談種類
          = f.collection_select :content_id, Content.all, :id, :name, {prompt: "--"}
          %span.require 必須
        .field
          = f.label :対応年月日
          %span.require 必須
          %br/  
          .wrap
            .select
              = f.select :year, [], {prompt: "--"}, {class: "select-year"}
            %span 年
            .select
              = f.select :month, [], {prompt: "--"}, {class: "select-month"}
            %span 月
            .select
              = f.select :day, [], {prompt: "--"}, {class: "select-day"}
            %span 日

        .field
          = f.label :商談内容
          %span.require 必須
          %br/
          = f.text_area :body, class:"negotiation-body require-check-body"

        .field
          = f.label :重要度
          = f.select :importance, ["★", "★★", "★★★", "★★★★", "★★★★★"]

        .field
          = f.label :関係部署
          = f.collection_select :department_id, Department.all, :id, :name, {prompt: "--"}

        .field
          = f.label :応対方法
          %span.require 必須
          = f.select :way, ["面会", "電話", "メール", "書面", "その他"], {prompt: "--"}

        .field
          = f.label :次回対応
          = f.select :next_nego, ["あり", "なし", "未定"], {prompt: "--"}, {id: "next-nego"}

        .next-negotiation-box
        
        = f.submit '登録', class: "submit-btn submit-nego"

app/views/negotiations/show.html.haml
= render "shared/header"
.container
  .main-nego
    .main-nego__detail
      .main-nego__detail__head
        .main-nego__detail__head__title
          = link_to :back do
            %i.fas.fa-chevron-left
          %p.nego-title
            = @negotiation.title
        .main-nego__detail__head__title
          %p.nego-importance
            = @negotiation.importance
            = react_component 'Pin'
        .main-nego__detail__head__menu
          %i.fas.fa-angle-down
        .main-nego__detail__head__menu__window{ style: "display:none" }
          %li
            = link_to "編集", edit_negotiation_path, data: {"turbolinks" => false}, class: "menu-btn"
            %br/
          %li
            = link_to "削除", negotiation_path, method: :delete, class: "confirm-btn menu-btn"
      .main-nego__detail__head
        .main-nego__detail__head__title
          %p
            #{@negotiation.year}年 #{@negotiation.month}月 #{@negotiation.day}日
        .main-nego__detail__head__user
          %p
            関連部署：#{@negotiation.department.name}
          %p
            担当：#{@negotiation.user.last_name} #{@negotiation.user.first_name}
      .main-nego__detail__box
        .main-nego__detail__box__container
          %p.content
            = @negotiation.content.name
        .main-nego__detail__box__container
          %p
            = @negotiation.customer.name
      .main-nego__detail__box
        .main-nego__detail__box__body
          = safe_join(@negotiation.body.split("\n"), tag(:br))
      .main-nego__detail__box
        .main-nego__detail__box__container
          %p
            次回：
        - if @negotiation.next_nego == "あり"
          .main-nego__detail__box__container
            %p.next-nego-text
              #{@negotiation.next_year}年 #{@negotiation.next_month}月 #{@negotiation.next_day}日
        - else
          %p
            = @negotiation.next_nego
      .main-nego__detail__box
        .main-nego__detail__box__menu
          = link_to "経過登録", new_negotiation_continuation_path(@negotiation.id), data: {"turbolinks" => false}, class: "continuation-btn menu-btn"
          %a.comment-box-btn.menu-btn
            コメントする
          - if @negotiation.comments.length != 0
            %button{class: "comment-show-btn menu-btn"}
              %i.far.fa-comment
              = @negotiation.comments.length
      .main-nego__detail__box
        .main-nego__detail__box__comment{ style: "display:none" }
          = form_with model: @comment, url: negotiation_comments_path(@negotiation.id), local: true do |c|
            .field
              = c.label :コメント
              %span.cancel-btn
                %i.fas.fa-times-circle
              %br/
              = c.text_area :body, class: "comment-area"
              
              = c.submit 'コメントする', class: "comment-submit menu-btn"
          
    .main-nego__detail__box__comment-box{ style: "display:none" }
      = render partial: "comments/comment", collection: @comments

= render "continuations/continuation"
  